[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
board_microros_transport = serial
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit MCP4728@^1.0.9
	adafruit/Adafruit NeoPixel@^1.12.3
include_dir = include
lib_extra_dirs = /home/wtf/Arduino/libraries/
